name: MTDAP Pipeline

on:
  push:
    paths:
      - 'tenants/**'
      - 'infra/**'
      - 'main.tf'
      - 'variables.tf'

jobs:   
  terraform:
    runs-on: self-hosted

    env:
      TF_VAR_kube_host: ${{ secrets.KUBE_HOST }}
      TF_VAR_kube_cluster_ca_certificate: ${{ secrets.KUBE_CLUSTER_CA_CERTIFICATE }}
      TF_VAR_kube_client_certificate: ${{ secrets.KUBE_CLIENT_CERTIFICATE }}
      TF_VAR_kube_client_key: ${{ secrets.KUBE_CLIENT_KEY }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve